development:
  adapter: sqlite3
  encoding: unicode
  database: db/database.db
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: <%= ENV[‘DATABASE_HOST’] %>
  pool: 5